name: "Bug Pilot"
description: "Analyze bugs from previous build."
author: "Takuma Maruyama"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  log_file: 
    description: "The path of analyze logs"
    required: true

outputs:
  errors:
    description: "Analyze errors from the log file"
