name: "Bug Pilot"
description: "Analyze errors from previous build log."
author: "Takuma Maruyama"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
#  log-file:
#    description: "The path of analyze logs"
#    required: true
  run-id:
    description: "The run id of the target job for analyze logs."
    required: true
  job-name:
    description: "The name of target job for analyze logs. If set this, analyze summary can export precise link for the build log."
    required: true
    default: ""
  step-name:
    description: "The name of target job step for analyze logs. If set this, analyze summary can export precise link for the build log."
    required: true
    default: ""

outputs:
  errors:
    description: "Analyze errors from the log file"
